apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r4d18gik6-python
  janus-idp.io/tekton: r4d18gik6-python
  backstage.io/kubernetes-id: r4d18gik6-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r4d18gik6-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
