apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: r4d18gik6-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: r4d18gik6-python 
  name: r4d18gik6-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: r4d18gik6-python
    weight: 100 
